/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,html}"],
  theme: {
    extend: {
      fontFamily: {
        inter: ["var(--font-inter)", "sans-serif"],
        krona: ["var(--font-krona)", "sans-serif"],
        roboto: ["var(--font-roboto)", "sans-serif"],
      },
      fontWeight: {
        400: "var(--font-weight-400)",
        500: "var(--font-weight-500)",
        550: "var(--font-weight-550)",
        600: "var(--font-weight-600)",
        700: "var(--font-weight-700)",
      },
      fontSize: {
        "11px": "var(--text-11px)",
        sm: "var(--text-sm)",
        "14px": "var(--text-14px)",
        base: "var(--text-base)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "5xl": "var(--text-5xl)",
        "22px": "var(--text-22px)",
      },
      colors: {
        primary: "var(--color-primary)",
        headingColor: "var(--color-headding-color)",
        menuSubHeadingColor: "var(--color-menuSubHeadingColor)",
        cardTitle: "var(--color-cardTitle)",
        cardValue: "var(--color-cardValue)",
        textHeading: "var(--color-textHeading)",
        whiteColor: "var(--color-whiteColor)",
        progressBar: "var(--color-progressBar)",
        paragraph: "var(--color-paragraph)",
        paragraphBlack: "var(--color-paragraphBlack)",
        reloadBorder: "var(--color-reloadBorder)",
        verifyOtp: "var(--color-verifyOtp)",
        purpleColor: "var(--color-purpleColor)",
        validationSuccess: "var(--color-validationSucColor)",
        cancelPlanText: "var(--color-cancelPlanText)",
        customWhiteColor: "var(--color-customWhiteColor)",
        yellow: "var(--color-yellow)",
        customWhite: "var(--color-customWhite)",
        billingNumber: "var(--color-billingNumber)",
        green: "var(--color-green)",
        headingBlack: "var(--color-headingBlack)",
      },
      backgroundColor: {
        bgGrey: "var(--background-color-background-grey)",
        bgStoreCard: "var(--background-color-store-card)",
        bgReload: "var(--background-color-reloadBackground)",
        bgWhite: "var(--background-color-backgroundWhite)",
        bgButton: "var(--background-color-bgButton)",
        bgSubMenus: "var(--background-color-subMenus)",
        bgPrimary: "var(--background-color-primary)",
        bgGreen: "var(--background-color-green)",
        bgYellow: "var(--background-color-yellow)",
        bgMaroon: "var(--background-color-maroon)",
      },
      borderColor: {
        borderGrey: "var(--border-color-grey-border)",
        borderReload: "var(--border-color-reloadBorder)",
        borderBtn: "var(--border-color-btnBorder)",
        borderCardTitle: "var(--border-color-cardTitle)",
        borderSubHeading: "var(--border-color-menuSubHeadingColor)",
      },
      borderRadius: {
        custom4: "var(--radius-custom4px)",
        custom: "var(--radius-custom)",
        custom4x: "var(--radius-custom4x)",
        custom7: "var(--radius-custom7px)",
        custom8: "var(--radius-custom8px)",
        custom12: "var(--radius-custom12px)",
        custom18: "var(--radius-custom18px)",
        custom20: "var(--radius-custom20px)",
        custom28: "var(--radius-custom28px)",
        custom44: "var(--radius-custom44px)",
        custom80: "var(--radius-custom80px)",
        custom100: "var(--radius-custom100px)",
      },
      backgroundImage: {
        linearBg: "var(--background-image-linear-bg)",
        // mainBg: "var(--background-image-main-bg)",
      },
      screens: {
        sm: "var(--breakpoint-sm)",
        md: "var(--breakpoint-md)",
        lg: "var(--breakpoint-lg)",
        xl: "var(--breakpoint-xl)",
        "2xl": "var(--breakpoint-2xl)",
      },
    },
  },
  safelist: [
    "rounded-[12px]",
    "w-[400px]",
    "h-[805px]",
    "text-[20px]",
    "leading-[150%]",
    // Add any other custom classes you use dynamically
  ],
  plugins: [],
};
